include::p2p.adoc[]

include::p2p-design-philosophy.adoc[]

include::p2p-attacks.adoc[]

include::node-components.adoc[]

include::netgroupmanager.adoc[]

include::addrman.adoc[]

include::bootstrapping.adoc[]

////

=== CConnman

https://github.com/bitcoin/bitcoin/blob/v23.0/src/net.h#L761[`CConnman`^] es la clase en net que abre, mantiene y cierra conexiones con pares, gestiona sockets y lee/escribe mensajes en la red.

// For operations that are done on each connection in turn (e.g. reading from each socket in the socket handler thread, or passing messages to net_processing in the message handler thread), the common pattern is to:
//
// . lock `cs_vNodes`
// . make a copy of the `vNodes` vector
// . for each `CNode` object, increment an internal https://github.com/bitcoin/bitcoin/blob/92758699/src/net.h#L454[nRefCount] atomic counter.
// . release `cs_vNodes`
// . operate on each of the `CNode` objects in the `vNodes` copy in turn
// . decrement the `nRefCount` counter for each `CNode`
//
// This PR proposes to extract that pattern into an https://en.cppreference.com/w/cpp/language/raii[RAII] object called `NodesSnapshot`.
// It also changes the order of some logic in the socket handler thread.
// The motivation is to reduce https://stackoverflow.com/questions/1970345/what-is-thread-contention[lock contentions].

=== Estableciendo conexiones

`CConnman::Start()` primero intentará enlazar a cualquier dirección especificada en bind (y whitebind) (y servicios onion), junto con la configuración opcional de la interfaz I2P:

Luego agregamos cualquier dirección suministrada a través del argumento `-seednode` (cargado en `vSeedNodes`), y luego cargamos direcciones (si las hay) desde `peers.dat` y finalmente `anchors.dat`.
`anchors.dat` estará vacío en la primera ejecución, pero si luego estamos satisfechos con nuestra conexión a la red bitcoin (y tenemos un apagado limpio), nuestros dos pares de solo retransmisión de bloques salientes se guardarán en este archivo para ayudar en la conectividad en ejecuciones posteriores del programa.

Debido a que el segmento de red del código es multi-hilo, se configuran dos `CSemaphores` a continuación que controlan el número de conexiones que realiza el nodo.

.src/net.cpp#CConnman::Start
[source,cpp,options=nowrap]
----
    if (semOutbound == nullptr) {
        // initialize semaphore
        semOutbound = std::make_unique<CSemaphore>(std::min(m_max_outbound, nMaxConnections));
    }
    if (semAddnode == nullptr) {
        // initialize semaphore
        semAddnode = std::make_unique<CSemaphore>(nMaxAddnode);
    }
----

Después de esto llegamos a la inicialización principal del hilo con la siguiente lógica:

. Se crea un hilo (`ThreadSocketHandler`) que gestiona la aceptación (de nuevas) y la desconexión de conexiones antiguas.
. Si las semillas DNS no están deshabilitadas, se crea un hilo (`ThreadDNSAddressSeed`) para solicitar direcciones de las semillas DNS.
. Se crea un hilo (`ThreadOpenAddedConnections`) para iniciar conexiones manuales (proporcionadas al inicio).
. Un hilo (`ThreadOpenConnections`) para realizar conexiones desde direcciones en `addrman`.

Podría parecer que las semillas DNS se están probando antes que las conexiones manuales y cualquier dirección encontrada en `peers.dat`, sin embargo, una inspección más cercana de la función `CConnman::ThreadDNSAddressSeed` de 109 líneas revela que más de la mitad de esas líneas se dedican a intentar _no_ consultar las semillas DNS, como describe la lógica en los comentarios del código:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
// goal: only query DNS seed if address need is acute
// * If we have a reasonable number of peers in addrman, spend
//   some time trying them first. This improves user privacy by
//   creating fewer identifying DNS requests, reduces trust by
//   giving seeds less influence on the network topology, and
//   reduces traffic to the seeds.
// * When querying DNS seeds query a few at once, this ensures
//   that we don't give DNS seeds the ability to eclipse nodes
//   that query them.
// * If we continue having problems, eventually query all the
//   DNS seeds, and if that fails too, also try the fixed seeds.
//   (done in ThreadOpenConnections)
----

Vemos en esa función que si tenemos más de 1000 pares en nuestro `addrman` (`DNSSEEDS_DELAY_PEER_THRESHOLD`) dormiremos durante 5 minutos (`DNSSEEDS_DELAY_MANY_PEERS`) antes de consultar las semillas DNS, pero si conocemos menos de 1000 pares, solo dormiremos durante 11 segundos (`DNSSEEDS_DELAY_FEW_PEERS`):

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
const std::chrono::seconds seeds_wait_time = (addrman.size() >= DNSSEEDS_DELAY_PEER_THRESHOLD ? DNSSEEDS_DELAY_MANY_PEERS : DNSSEEDS_DELAY_FEW_PEERS);
----

Existe un riesgo donde un sembrador DNS malicioso eclipsa un nodo devolviendo una cantidad enorme de direcciones IP.
Mitigamos este riesgo limitando el número de direcciones IP que addrman aprende a 256 por sembrador DNS.
Más abajo en `ThreadDNSAddressSeed()` vemos tal número mágico:

.src/net.cpp#CConnman::ThreadDNSAddressSeed
[source,cpp,options=nowrap]
----
unsigned int nMaxIPs = 256; // Limits number of IPs learned from a DNS seed
----

Si después de 60 segundos no hemos realizado ninguna conexión, entonces `ThreadOpenConnections` deserializará las semillas codificadas y las https://github.com/bitcoin/bitcoin/blob/v23.0/src/net.cpp#L1960-L1987[agregará^] a xref:addrman.adoc#[addrman] como candidatos para la conexión.
////

include::message-relay.adoc[]

include::address-relay.adoc[]

include::transaction-relay.adoc[]

include::block-relay.adoc[]

include::relay-preferences.adoc[]

include::p2p-encryption.adoc[]

include::network-entropy.adoc[]

include::peer-state.adoc[]

include::p2p-violations.adoc[]

include::testing-p2p-changes.adoc[]

include::p2p-exercises.adoc[]
