= Mempool

include::mempool-terminology.adoc[]

include::mempool-purpose.adoc[]

include::mempool-lifecycle.adoc[]

include::addition-removal-mempool.adoc[]

include::mempool-unbroadcast.adoc[]

include::mempool-tx-format.adoc[]

include::package-relay.adoc[]

include::pinning-attacks.adoc[]

////

== MemPoolAccept

La clase `MemPoolAccept` maneja la validación del mempool para nuevas transacciones.

Seleccionar las mejores transacciones para el mempool, que tiene recursos limitados, implica un equilibrio entre validar optimistamente los candidatos para identificar aquellos con la tarifa más alta y proteger el nodo de ataques DoS.
Por lo tanto, aplicamos un conjunto de reglas de validación conocidas como _política_ del mempool además del consenso.

Podemos desglosar las verificaciones de validación de transacciones en algunas clases diferentes:

* Consenso vs Política: Estas también pueden considerarse como verificaciones obligatorias vs no obligatorias.
Estas dos no son mutuamente excluyentes, pero hacemos esfuerzos para compartimentar las reglas de consenso.
* Script vs No-script: Script se refiere a las instrucciones y datos utilizados para especificar y cumplir las condiciones de gasto.
Hacemos esta distinción porque la verificación de scripts (específicamente, la verificación de firmas) es la parte más intensiva en computación de la validación de transacciones.
* Contextual vs Sin contexto: El contexto se refiere a nuestro conocimiento del estado actual, representado como https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.h#L459[ChainState^].
Las verificaciones contextuales pueden requerir la altura actual del bloque o el conocimiento del conjunto UTXO actual, mientras que las verificaciones sin contexto solo necesitan la transacción en sí.
También necesitamos mirar nuestro mempool para validar una transacción que gasta padres no confirmados o que entra en conflicto con otra transacción ya en nuestro mempool.

=== Verificaciones sin contexto y sin script

La validación del mempool en Bitcoin Core comienza con verificaciones sin script (a veces llamadas https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L668["PreChecks"^], el nombre de la función en la que se ejecutan estas verificaciones).

Como estrategia defensiva, el nodo comienza con verificaciones sin contexto y/o fácilmente calculables.
Aquí hay algunos ejemplos:

* Ninguno de los salidas está tratando de enviar un valor https://github.com/bitcoin/bitcoin/blob/v23.0/src/consensus/tx_check.cpp#L26-L29[menor que 0 o mayor que 21 millones de BTC^].
* La transacción https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L689-L691[no es una coinbase^], ya que no puede haber transacciones coinbase fuera de los bloques.
* La transacción no es https://github.com/bitcoin/bitcoin/blob/v23.0/src/policy/policy.cpp#L93-L95[más de 400,000 unidades de peso^].
+
Es posible que una transacción más grande sea válida por consenso, pero ocuparía demasiado espacio en el mempool.
Si permitiéramos estas transacciones, un atacante podría intentar dominar nuestro mempool con transacciones muy grandes que nunca se minan.

=== Verificaciones contextuales sin script

Quizás la verificación contextual sin script más obvia es https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L750-L771[asegurarse de que las entradas estén disponibles^], ya sea en el estado actual de la cadena o como una salida no gastada de una transacción en el mempool.
En lugar de buscar en toda la cadena de bloques (cientos de gigabytes almacenados en disco), los nodos de Bitcoin Core mantienen una https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.h#L410-L434[caché en capas^] de las https://github.com/bitcoin/bitcoin/blob/v23.0/src/coins.h#L30[monedas^] disponibles, que son unos pocos gigabytes, gran parte de los cuales se pueden mantener en memoria.
Para hacer este proceso más eficiente, las monedas obtenidas del disco durante la validación del mempool se https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1370-L1378[mantienen en memoria^] si la transacción es aceptada en el mempool.

Los bloqueos de tiempo también se verifican aquí: el nodo obtiene el BIP113 Median Time Past y/o la altura del bloque en el estado actual de la cadena para verificar `nLockTime` de la transacción y `nSequence` de la entrada.

=== Verificaciones de Script "Contextuales"

Las https://doxygen.bitcoincore.org/validation_8cpp.html#a6a96a3e1e6818904fdd5f51553b7ea60[verificaciones de script^] de transacciones son en realidad sin contexto en aislamiento; el https://doxygen.bitcoincore.org/class_c_tx_in.html#aba540fd902366210a6ad6cd9a18fe763[`scriptSig`^] y el https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#specification[`witness`^] para cada entrada, emparejados con el https://doxygen.bitcoincore.org/class_c_tx_out.html#a25bf3f2f4befb22a6a0be45784fe57e2[`scriptPubKey`^] en el https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1698[UTXO correspondiente^] pueden pasarse al intérprete de scripts y validarse sin estado.
El https://doxygen.bitcoincore.org/interpreter_8h.html[intérprete de scripts^] simplemente evalúa la serie de opcodes y datos basados en los argumentos que se le pasan.

El "contexto" pasado al intérprete de scripts es un conjunto de https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.h#L43-L147[banderas de verificación de scripts^] que indican qué reglas aplicar durante la verificación de scripts.
Por ejemplo, el opcode `OP_CHECKSEQUENCEVERIFY` reutilizó `OP_NOP3`.
La bandera de verificación de scripts `SCRIPT_VERIFY_CHECKSEQUENCEVERIFY` instruye al intérprete de scripts https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.cpp#L587[a interpretar^] el opcode `0xb2` como la instrucción para verificar que el `nSequence` de la entrada sea mayor que el valor de la pila o como una operación nula. A partir de la altura de activación de BIP112, https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1893-L1896[los nodos pasan^] `SCRIPT_VERIFY_CHECKSEQUENCEVERIFY=1` al intérprete de scripts durante las verificaciones de scripts de consenso.

=== Verificaciones de Firma y Script sin Contexto

La validación del mempool realiza dos conjuntos de verificaciones de scripts: https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L973[`PolicyScriptChecks`^] y https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1001[`ConsensusScriptChecks`^].
El primero ejecuta el intérprete de scripts utilizando las banderas de consenso y política y almacena en caché el resultado de la firma (si tiene éxito) en la https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/sigcache.cpp#L21-L26[caché de firmas^].
El segundo ejecuta el intérprete de scripts utilizando https://github.com/bitcoin/bitcoin/blob/v23.0/src/validation.cpp#L1025[solo banderas de consenso^] y almacena en caché el resultado completo de la validación en la caché de ejecución de scripts, identificado por el wtxid y las banderas de verificación de scripts.
Si se activa una nueva regla de consenso entre ahora y el bloque en el que se incluye esta transacción, el resultado almacenado en caché ya no es válido, pero esto se detecta fácilmente en función de las banderas de verificación de scripts.

Por ejemplo, antes de que las reglas de taproot se apliquen en el consenso, están en la política (`SCRIPT_VERIFY_TAPROOT` incluido en las banderas de verificación de scripts de política pero no en las de consenso); los nodos no retransmitirán ni aceptarán transacciones de versión 1 inválidas por taproot en sus mempools, aunque aún no estén rompiendo ninguna regla de consenso.
Todas las verificaciones de scripts se almacenarán en caché sin `SCRIPT_VERIFY_TAPROOT`.
Después de la activación de taproot, si se ve una transacción previamente validada, las banderas de verificación de scripts de la entrada en caché no coincidirán con las banderas de consenso actuales, por lo que el nodo volverá a ejecutar las verificaciones de scripts para esa transacción.

La parte más intensiva en computación de la validación de scripts es la verificación de firmas (indicada en un script por opcodes como `OP_CHECKSIG`), que no cambia según el contexto.
Para ahorrar al nodo trabajo repetitivo, al inicio de las verificaciones de scripts, partes de la transacción se https://github.com/bitcoin/bitcoin/blob/v23.0/src/script/interpreter.cpp#L1423[serializan, hashean y almacenan^] en una estructura `PrecomputedTransactionData` para su uso en la verificación de firmas.
Esto es especialmente útil en transacciones que tienen múltiples entradas y/o firmas.
Además, el resultado almacenado en caché de `PolicyScriptChecks` se puede usar inmediatamente en `ConsensusScriptChecks`; ¡casi nunca necesitamos verificar la misma firma más de una vez!

////
