= Uso del formato asciidoc

El formato https://asciidoctor.org/[asciidoc] se ha utilizado para esta documentación.

Para usar el formato asciidoc, asegúrate de que la herramienta `asciidoctor` esté instalada (y en tu $PATH del sistema).
Además, puede ser útil asegurarte de que tu editor entienda el tipo de archivo, por ejemplo, para Vim puedes instalar https://github.com/habamax/vim-asciidoctor[vim-asciidoctor].

Una referencia rápida para el formato asciidoc se puede encontrar https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[aquí].

Esta documentación sigue la práctica recomendada de asciidoc de https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[Una Oración Por Línea]. 
Si decides contribuir (¡gracias!), por favor trata de continuar con esta práctica para facilitar la edición futura.

== Generar _index.html_ para alojamiento web estático

Puedes generar un archivo _index.html_ para alojamiento web estático instalando la herramienta <<asciidoctor>> y luego ejecutando:

[source,bash]
----
asciidoctor index.adoc
----

Simplemente aloja _index.html_ junto con el directorio _images/_ y su contenido en la raíz de tu servidor web para servir la documentación.

=== Añadir diagramas mermaid

Si añades un diagrama mermaid a un artículo, debes añadir:

----
:mermaid-puppeteer-config: ./puppeteer-config.json
----

Al encabezado del archivo, para que el contenedor/Dockerfile pueda hacer que mermaid-cli pase la configuración de puppeteer a puppeteer.

=== Regenerar diagramas mermaid

Para regenerar los diagramas mermaid, necesitarás https://github.com/mermaid-js/mermaid-cli[mermaid-cli] y https://docs.asciidoctor.org/diagram-extension/latest/[asciidoctor-diagram]

Con ambos programas en tu PATH, puedes ejecutar el comando:

[source,shell]
----
asciidoctor -r asciidoctor-diagram index.adoc
----

Para generar index.html, junto con las imágenes requeridas en el subdirectorio `/images`.

=== Actualizar _index.html_ automáticamente como un hook de pre-commit

Si prefieres, puedes escribir un simple hook de pre-commit para actualizar el archivo _index.html_ automáticamente en cada commit.
Un ejemplo de esto podría ser:

._$PROJECT_ROOT/.git/hooks/pre-commit_
[source,bash]
----
#!/usr/bin/bash

asciidoctor index.adoc
----
