:page-title: BIPs
:page-nav_order: 180
:page-parent: Overview and Development Process
[[bips]]
== BIPs

Bitcoin utiliza Propuestas de Mejora de Bitcoin (BIPs) como un documento de diseño para introducir nuevas características o comportamientos en bitcoin.
Bitcoin Magazine describe qué es un BIP en su artículo https://bitcoinmagazine.com/guides/what-is-a-bitcoin-improvement-proposal-bip[¿Qué es una Propuesta de Mejora de Bitcoin (BIP)^], destacando específicamente cómo los BIPs no son necesariamente documentos vinculantes requeridos para lograr consenso.

Los BIPs están actualmente alojados en GitHub en el repositorio bitcoin/bips https://github.com/bitcoin/bips[repo^].

[TIP]
.Proceso BIP
====
Los BIPs incluyen https://github.com/bitcoin/bips/tree/master/bip-0002.mediawiki[BIP 2^] que se describe a sí mismo el proceso BIP con más detalle.
De particular interés podrían ser las secciones https://github.com/bitcoin/bips/tree/master/bip-0002.mediawiki#BIP_types[Tipos de BIP^] y https://github.com/bitcoin/bips/tree/master/bip-0002.mediawiki#BIP_workflow[Flujo de trabajo de BIP^].
====

=== ¿Qué significa tener un número BIP asignado a una idea?

El https://github.com/bitcoin/bitcoin/pull/22665[issue #22665^] de Bitcoin Core describió cómo BIP125 no se estaba cumpliendo estrictamente por Bitcoin Core.
Esto generó una discusión entre los desarrolladores sobre si el código (es decir, "la implementación") o el propio BIP debería actuar como la especificación, con la mayoría de los desarrolladores expresando que sentían que "el código era la especificación" y cualquier BIP generado era simplemente un documento de diseño para ayudar con la reimplementación por otros, y debería corregirse si fuera necesario.

NOTA: Esta opinión no fue completamente unánime en la comunidad.

Para el código crítico para el consenso, la mayoría de los desarrolladores de Bitcoin Core consideran que "el código es la especificación" es la fuente última de verdad, lo cual es una de las razones por las que recomendar ejecutar otras implementaciones de nodos completos puede ser tan difícil.
Un efecto secundario de esto fue que hubo llamados a revisar el propio BIP2, con respecto a cómo deberían actualizarse/modificarse los BIPs.
El recién nombrado mantenedor de BIP, Karl-Johan Alm (también conocido como kallewoof), publicó sus pensamientos sobre esto en la https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-September/019457.html[lista de correo bitcoin-dev^].

En resumen, un BIP representa un documento de diseño que debería ayudar a otros a implementar una característica específica de manera compatible.
Estas características son opcionales para el uso de Bitcoin, y por lo tanto la implementación de BIPs no es necesaria para usar Bitcoin, solo para mantener la compatibilidad.
Simplemente ser _asignado_ un BIP *no* significa que una idea esté respaldada como una "buena" idea, solo que está completamente especificada de una manera que otros podrían usar para reimplementar.
Muchas ideas son asignadas un BIP y luego nunca se implementan o usan en la red más amplia.
