:page-title: Construyendo Bitcoin Core
:page-nav_order: 70
:page-parent: Overview and Development Process
=== Compilación desde el código fuente

Al compilar Bitcoin Core desde el código fuente, hay algunas instrucciones dependientes de la plataforma que se deben seguir.

Para aprender cómo compilar para tu plataforma, visita el directorio https://github.com/bitcoin/bitcoin/tree/master/doc[bitcoin/doc^] de Bitcoin Core, y lee el archivo llamado "build-\*.md", donde "*" es el nombre de tu plataforma.
Para Windows esto es "build-windows.md", para macOS esto es "build-osx.md" y para la mayoría de las distribuciones de Linux esto es "build-unix.md".

También hay una guía de Jon Atack sobre cómo https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests[compilar y probar Bitcoin Core^].

Finalmente, Blockchain Commons también ofrece una guía para https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/A2_0_Compiling_Bitcoin_from_Source.md[compilar desde el código fuente^].

==== Compilaciones más limpias

Puede ser útil usar un directorio de compilación separado, por ejemplo, `build/` al compilar desde el código fuente.
Esto puede ayudar a evitar errores espurios del enlazador sin requerir que ejecutes `make clean` con frecuencia.

Desde dentro de tu directorio de código fuente de Bitcoin Core puedes ejecutar:

[source,bash]
----
# Limpiar el directorio de código fuente actual en caso de que ya esté configurado
make distclean

# Crear un nuevo directorio de compilación
mkdir build && cd build

# Ejecutar la secuencia de compilación normal con la ruta enmendada
../autogen.sh
../configure --your-normal-options-here
make -j `nproc`
make check
----

[TIP]
====
Para ejecutar pruebas funcionales individuales usando el binario bitcoind compilado en una compilación fuera del código fuente, cambia el directorio de nuevo a la raíz del código fuente y especifica el archivo _config.ini_ desde dentro del directorio de compilación:

[source,bash]
----
$ pwd
/path/to/source/build
$ cd ..
$ test/functional/p2p_ping.py --configfile build/test/config.ini
----
====
