:page-title: Canales de comunicación
:page-nav_order: 120
:page-parent: Descripción general y proceso de desarrollo
=== Canal #bitcoin-core-dev en IRC

El proyecto Bitcoin Core tiene un canal de IRC `#bitcoin-core-dev` disponible en la red Libera.chat.
Si no estás familiarizado con IRC, hay una guía corta sobre cómo usarlo con un cliente llamado Matrix https://hackmd.io/ZcCoEDnOSTSqb2RDa7fB8Q[aquí^].
Hay clientes de IRC disponibles para todas las plataformas y muchos terminales.

"Merodear" (observar pero no hablar) en el canal de IRC puede ser una excelente manera de aprender sobre nuevos desarrollos, así como observar cómo se describen y piensan los nuevos cambios técnicos y problemas desde otros desarrolladores con una mentalidad adversarial.
¡Una vez que te sientas cómodo con las reglas de la sala y tengas preguntas sobre el desarrollo, también puedes unirte!

[NOTE]
====
Este canal está reservado para la discusión sobre _el desarrollo del software Bitcoin Core solamente_, así que por favor no hagas preguntas generales sobre Bitcoin ni hables sobre el precio u otras cosas que estarían fuera de tema allí.

Hay muchos otros canales en IRC donde esos temas pueden ser discutidos.
====

También se celebran reuniones regulares en #bitcoin-core-dev que son gratuitas y abiertas para que cualquiera pueda asistir.
Los detalles y horarios de las diversas reuniones se encuentran https://bitcoincore.org/en/meetings/[aquí^].

=== Comunicación

En realidad no hay reglas estrictas para elegir un foro de discusión, pero en la práctica hay algunas convenciones comunes que generalmente se siguen:

* Si deseas discutir la base de código de la implementación de Bitcoin Core, entonces la discusión en el repositorio de GitHub o en el canal de IRC suele ser lo más apropiado.
* Si deseas discutir cambios en el protocolo central de bitcoin, entonces la discusión en la lista de correo generalmente es necesaria para solicitar comentarios de (todos) los desarrolladores de bitcoin, incluidos muchos de ellos que no trabajan directamente en Bitcoin Core.
** Si las discusiones en la lista de correo parecen indicar interés por una propuesta, entonces generalmente sigue la creación de un BIP.

Si estás discutiendo algo relacionado con Bitcoin Core, también puede surgir la pregunta de si es mejor abrir un Issue, para primero discutir el problema y pensar en posibles enfoques de solución, o si deberías implementar los cambios como mejor te parezca primero, abrir un PR y luego discutir los cambios en el PR.
Nuevamente, no hay reglas estrictas aquí, pero el consejo general sería que para temas potencialmente controvertidos, podría valer la pena abrir un Issue primero, antes de (potencialmente) perder tiempo implementando una solución PR que es poco probable que sea aceptada.

En cuanto a los tiempos de comunicación, es importante recordar que muchos colaboradores son voluntarios no remunerados, e incluso si están patrocinados o pagados directamente, nadie te debe su tiempo.
Dicho esto, a menudo durante la comunicación de ida y vuelta, es posible que desees empujar a alguien para obtener una respuesta y es importante que lo hagas de manera cortés.
Nuevamente, no hay reglas estrictas aquí, pero a menudo es una buena práctica dar a alguien del orden de unos pocos días a una semana para responder.
Recuerda que las personas tienen vidas personales y a menudo trabajos fuera del desarrollo de Bitcoin.
