:page-title: Descripción general de bitcoind
:page-nav_order: 20
:page-parent: Arquitectura
:mermaid-puppeteer-config: ./puppeteer-config.json
== Descripción general de bitcoind

El siguiente diagrama ofrece una breve descripción de cómo se relacionan algunos de los componentes principales de bitcoind.

ADVERTENCIA: Este diagrama **no** es exhaustivo e incluye simplificaciones.

NOTA: las líneas discontinuas indican componentes opcionales

.`bitcoind` descripción general
[mermaid, target=bitcoind-overview, id=bitcoind-overview]
....
flowchart LR
    bitcoind
    RPCServer -.-> bitcoind
    RESTServer -.-> bitcoind
    Node -----> bitcoind
    AddrMan --> Node
    CConnman --> Node
    Interfaces::Chain --> Node
    ChainstateManager --> Node
    NetGroupManager --> AddrMan
    CTxMemPool --> Node
    PeerManager --> Node
    Wallet -.-> bitcoind
    ScriptPubKeyMan --> Wallet
    WalletDatabase --> Wallet
    sqlite -.-> WalletDatabase
    BDB -.-> WalletDatabase
    Logger --> bitcoind
    ZMQ -.-> bitcoind
    BlockManager --> ChainstateManager
    LevelDB --> BlockManager
....

.Breve descripción de los componentes en <<bitcoind-overview>>
[%autowidth]
|===
|Componente |Descripción simplificada

|`AddrMan`
|Gestiona las direcciones de red de los pares

|`CConnman`
|Gestiona las conexiones de red con los pares

|`Interfaces::Chain`
|Proporciona a los clientes acceso al estado de la cadena, estimaciones de tarifas, notificaciones y permite la presentación de transacciones

|`ChainstateManager`
|Una interfaz para interactuar con 1 o 2 estados de la cadena (1. Verificado por IBD, 2. instantánea opcional)

|`NetGroupManager`
|Gestiona los grupos de red. Asegura que no nos conectemos a múltiples nodos en el mismo grupo ASN

|`CTxMemPool`
|Valida y almacena transacciones (válidas) que pueden incluirse en el próximo bloque

|`PeerManager`
|Gestiona el estado e interacción de los pares, por ejemplo, procesando mensajes, obteniendo bloques y eliminando por mal comportamiento

|`BlockManager`
|Mantiene un árbol de bloques en disco (a través de LevelDB) para determinar la punta de mayor trabajo

|`ScriptPubKeyMan`
|Gestiona `scriptPubKeys` en una billetera. Puede proporcionar nuevos `scriptPubKeys` así como llamar a un `SigningProvider` para firmar transacciones

|===

== Descripción general de `bitcoin-cli`

El siguiente diagrama ofrece una breve descripción de los componentes principales en bitcoin-cli.

ADVERTENCIA: Este diagrama **no** es exhaustivo e incluye simplificaciones.

.`bitcoin-cli` descripción general
[mermaid, target=bitcoin-cli-overview, id=bitcoin-cli-overview-chart]
....
flowchart LR
    BaseRequestHandler["BaseRequestHandler()"]
    AddrInfoRequestHandler["AddrInfoRequestHandler()"]
    ConnectAndCallRPC["ConnectAndCallRPC()"]
    GetInfoRequestHandler["GetInfoRequestHandler()"]
    NetInfoRequestHandler["NetInfoRequestHandler()"]
    GenerateToAddressHandler["GenerateToAddressHandler()"]
    DefaultRequestHandler["DefaultRequestHandler()"]
    BaseRequestHandler --> AddrInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> GetInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> NetInfoRequestHandler --> ConnectAndCallRPC
    BaseRequestHandler --> GenerateToAddressHandler --> ConnectAndCallRPC
    BaseRequestHandler --> DefaultRequestHandler --> ConnectAndCallRPC
    ConnectAndCallRPC <---> bitcoin-cli
    ArgsManager --> bitcoin-cli
....

== Estructura de la billetera

El siguiente diagrama ofrece una breve descripción de cómo está estructurada la billetera.

ADVERTENCIA: Este diagrama **no** es exhaustivo e incluye simplificaciones.

NOTA: las líneas discontinuas indican componentes opcionales

.Descripción general de la estructura de la billetera
[mermaid, target=bitcoin-wallet-overview]
....
flowchart LR
    ScriptPubKeyMan --> DescriptorScriptPubKeyMan
    ScriptPubKeyMan --> LegacyScriptPubKeyMan
    subgraph Descriptor or Legacy wallet
    DescriptorScriptPubKeyMan
    LegacyScriptPubKeyMan
    end
    DescriptorScriptPubKeyMan -.-> CWallet
    LegacyScriptPubKeyMan -.-> CWallet
    Interfaces::Chain --> CWallet
    WalletDatabase --> CWallet
    cs_wallet{{cs_wallet}} ---> CWallet

    subgraph BDB or sqlite database
    BDB
    sqlite
    end
    BDB -.-> WalletDatabase
    sqlite -.-> WalletDatabase

    SigningProvider --> ScriptPubKeyMan
    WalletStorage --> ScriptPubKeyMan
    Scripts --> ScriptPubKeyMan
    Keys --> ScriptPubKeyMan
....

.Breve descripción de los componentes
[%autowidth]
|===
|Componente |Descripción simplificada

|`WalletDatabase`
|Representa una sola billetera. Maneja lecturas y escrituras en disco

|`ScriptPubKeyMan`
|Clase base para las clases SPKM a continuación que se sobrescriben antes de ser utilizadas por `CWallet`

|`DescriptorScriptPubKeyMan`
|Un SPKM para billeteras basadas en descriptores

|`LegacyScriptPubKeyMan`
|Un SPKM para billeteras heredadas

|`SigningProvider`
|Una interfaz para un `KeyStore` para firmar transacciones

|`Interfaces::Chain`
|Proporciona a los clientes acceso al estado de la cadena, estimaciones de tarifas, notificaciones y permite la presentación de transacciones

|`cs_wallet`
|El bloqueo principal de la billetera, mantenido para operaciones atómicas de la billetera
|===

|===
