:page-nav_order: 20
:page-has_children: true
include::links-onepage.adoc[]
= Consenso y Validación

TIP: Esta sección ha sido actualizada a Bitcoin Core @ https://github.com/bitcoin/bitcoin/tree/v23.0[v23.0^]

Uno de los conceptos fundamentales subyacentes al bitcoin es que los nodos en la red son capaces de mantener un consenso descentralizado sobre el orden de las transacciones en el sistema.

El mecanismo principal en funcionamiento es que todos los nodos validan cada bloque, y cada transacción contenida en ese bloque, contra su propia copia de las reglas de consenso.
El mecanismo secundario es que en caso de discrepancia entre dos cadenas competidoras, los nodos deben seguir la cadena con la mayor prueba de trabajo acumulada.
El resultado es que todos los nodos honestos en la red eventualmente convergerán en una única cadena válida y canónica.

ADVERTENCIA: Si todos los nodos no calculan los valores de consenso de manera idéntica (incluyendo casos extremos) se producirá una división de cadenas.

Para obtener más información sobre cómo funciona el mecanismo de consenso descentralizado de las redes de bitcoin, consulte la sección de Mastering Bitcoin en https://github.com/bitcoinbook/bitcoinbook/tree/develop/ch10.asciidoc#decentralized-consensus[consenso descentralizado^].

TIP: En Bitcoin Core hay un nivel adicional de verificaciones de validación aplicadas a las transacciones entrantes además de las verificaciones de consenso llamadas "política", que tienen un propósito ligeramente diferente, consulte xref:consensus-v-policy.adoc#consensus_vs_policy[consenso vs política] para obtener más información sobre las diferencias entre ambos.

Consenso::
Una colección de funciones y variables que **deben** ser calculadas de manera idéntica por todos los https://bitnodes.io/nodes/[otros^] nodos en la red para permanecer en consenso y, por lo tanto, en la cadena principal.

Validación::
Validación de bloques, transacciones y scripts, con el fin de permitir que se añadan a la blockchain (deben pasar las verificaciones de consenso) o a nuestro mempool local (deben pasar las verificaciones de política).
