:page-title: Roles del proyecto
:page-nav_order: 160
:page-parent: Overview and Development Process
== Organización y roles

El objetivo de la Organización de Bitcoin Core es representar una entidad que esté descentralizada tanto como sea prácticamente posible en una plataforma centralizada.
Una donde ningún Colaborador, Miembro o Mantenedor tenga control unilateral sobre lo que se fusiona o no en el proyecto.
Tener múltiples Mantenedores, Miembros, Colaboradores y Revisores da a este objetivo la mejor oportunidad de ser realizado.

=== Colaboradores

Cualquiera que contribuya con código a la base de código es etiquetado como Colaborador por GitHub y también por la comunidad.
A partir de la Versión 23.0 de Bitcoin Core, hay más de 850 Colaboradores individuales acreditados con cambios.

=== Miembros

Algunos Colaboradores también son etiquetados como Miembros de la https://github.com/orgs/bitcoin/people[organización Bitcoin^].
No hay criterios definidos para convertirse en Miembro de la organización; las personas son usualmente nominadas para su adición o remoción por un Mantenedor/Miembro/Admin actual de manera ad-hoc.
Los Miembros son típicamente Colaboradores/Revisores frecuentes y tienen buen conocimiento técnico de la base de código.

Algunos miembros también tienen algunos permisos adicionales sobre los Colaboradores, como agregar/eliminar etiquetas en problemas y Solicitudes de Extracción (PRs); sin embargo, ser Miembro **no** te permite fusionar PRs en el proyecto.
Los Miembros también pueden ser asignados a secciones de la base de código en las que tienen experiencia específica para ser más fácilmente solicitados para revisión como Revisores Sugeridos por los autores de PR.

////
NOTA: No es ni necesario ni deseable "solicitar revisiones" de los revisores sugeridos en un flujo de trabajo normal. Hacerlo sin una buena razón podría interpretarse como ser insistente y tener el resultado opuesto al deseado.
////

=== Mantenedores

Algunos Miembros de la organización también son Mantenedores del proyecto.
El número de mantenedores es arbitrario y está sujeto a cambios a medida que las personas se unen y dejan el proyecto, pero históricamente ha sido menos de 10.
Los PRs solo pueden ser fusionados en el proyecto principal por los Mantenedores.
Aunque esto podría dar la ilusión de que los Mantenedores están en control del proyecto, el rol de los Mantenedores dicta que *no deberían* decidir unilateralmente qué PRs se fusionan y cuáles no.
En cambio, deberían determinar la posibilidad de fusión de los cambios basándose principalmente en las revisiones y discusiones de otros Colaboradores en el PR de GitHub.

Trabajando sobre esa base, el rol de los Mantenedores se vuelve en gran medida _janitorial_.
Simplemente están ejecutando los deseos del proceso de revisión comunitaria, una comunidad que está compuesta por un grupo descentralizado y diverso de Colaboradores.

////
Una lista de Mantenedores y Revisores sugeridos se puede encontrar en el documento https://github.com/bitcoin/bitcoin/tree/master/REVIEWERS[REVIEWERS^].
Como indica el documento, estas *no* son las únicas personas que deberían estar revisando PRs.
El proyecto necesita tantas revisiones en cada PR como sea posible, idealmente de una gama diversa de Revisores.
////

=== Salvaguardias de la organización

Es posible que un "PR rebelde" sea enviado por un Colaborador; confiamos en una revisión sistemática y exhaustiva por pares para detectarlos.
Ha habido https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-September/019490.html[discusión^] en la lista de correo sobre enviar intencionalmente PRs maliciosos para probar la robustez de este proceso de revisión.

En el caso de que un Mantenedor se vuelva rebelde y comience a fusionar código controvertido, o por el contrario, _no_ fusionar cambios que son deseados por la comunidad en general, entonces hay dos posibles vías de recurso:

. Hacer que el Mantenedor Principal elimine al Mantenedor malicioso
. En el caso de que el propio Mantenedor Principal sea considerado el agente rebelde: bifurcar el proyecto a una nueva ubicación y continuar el desarrollo allí.

En el caso de que GitHub mismo se convierta en la entidad rebelde, ha habido numerosas discusiones sobre cómo alejarse de GitHub, que han sido resumidas en el devwiki https://github.com/bitcoin-core/bitcoin-devwiki/wiki/GitHub-alternatives-for-Bitcoin-Core[aquí^].
Este resumen provino en parte de discusiones en https://github.com/bitcoin/bitcoin/issues/20227[este^] problema de GitHub.
