:page-title: Contribución de código
:page-nav_order: 30
:page-parent: Descripción general y proceso de desarrollo
=== Contribución de código

Esta sección detalla algunos de los procesos relacionados con las contribuciones de código al proyecto Bitcoin Core, junto con algunos escollos comunes y consejos para tratar de evitarlos.

==== Ramas

No debes usar la rama incorporada de GitHub https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository[para crear ramas y eliminarlas^].

En su lugar, debes usar las herramientas nativas https://git-scm.com/downloads[`git`^] o el https://github.com/cli/cli[`gh` cli^] de GitHub (requiere `git`) para crear tus propias ramas localmente, antes de subirlas a tu fork.

==== Creación de una PR

El artículo de Jon Atack https://jonatack.github.io/articles/how-to-contribute-pull-requests-to-bitcoin-core[How To Contribute Pull Requests To Bitcoin Core^] describe algunos requisitos menos obvios para abrir una PR.
También describe la expectativa no codificada de que los Contribuidores no solo deberían estar escribiendo código, sino quizás más importante, proporcionando revisiones sobre los PRs de otros Contribuidores.
A la mayoría de los desarrolladores les gusta escribir su propio código más que revisar el código de otros, pero el proceso de revisión descentralizado es posiblemente la defensa más crítica que tiene el desarrollo de Bitcoin contra cambios maliciosos.

IMPORTANTE: Las estimaciones de Jon de "5-15 revisiones de PR|problemas resueltos" por PR presentado no son un requisito estricto, solo lo que Jon mismo considera mejor para el proyecto. No te desanimes por enviar una PR si no has revisado tantos PRs.

Para algunos consejos sobre cómo mantener un PR abierto usando git, como rehacer el historial de commits, así como editar commits específicos, consulta esta https://github.com/satsie/bitcoin-notez/blob/master/bitcoin-notez-PR.md[guía^].

==== Mensajes de commits

Cuando escribas mensajes de commits asegúrate de haber leído la publicación de blog de Chris Beams "Cómo Escribir un Mensaje de Commit de Git" https://chris.beams.io/posts/git-commit/[post^].
Como se describe en CONTRIBUTING.md, los PRs deben estar prefijados con el componente o área que afecta el PR.
Las áreas comunes están listadas en la sección CONTRIBUTING.md: https://github.com/bitcoin/bitcoin/tree/master/CONTRIBUTING.md#creating-the-pull-request[Creating the pull request^].
Los mensajes de commits individuales también suelen tener prefijos similares en el título del commit dependiendo de qué área del código se ve principalmente afectada.

[CONSEJO]
====
A menos que haya un conflicto de fusión (generalmente detectado por DrahtBot), no rehagas el rebase de tus cambios en la rama master antes de hacer push.
Si evitas los rebases en upstream, GitHub mostrará un botón de "Comparar" muy útil que los revisores pueden usar a menudo para volver a aprobar rápidamente los nuevos cambios si son lo suficientemente pequeños.
Si haces rebase, este botón se vuelve inútil, ya que todos los cambios rehechos de master se incluyen y puede ser necesaria una revisión completa.
¡El tiempo de revisión de los desarrolladores es actualmente nuestro principal cuello de botella en el proyecto!
====
