:page-title: Depurando Bitcoin Core
:page-nav_order: 50
:page-parent: Descripción general y proceso de desarrollo
==== Depuración de Bitcoin Core

// Archivado en https://archive.is/hRExH
Fabian Jahr ha creado una https://github.com/fjahr/debugging_bitcoin[guía^] sobre "Depuración de Bitcoin Core", destinada a detallar las formas en que se pueden depurar varios componentes de Bitcoin Core, incluido el binario de Bitcoin Core, pruebas unitarias, pruebas funcionales junto con una introducción a los volcados de núcleo y la suite de detección de fugas de memoria Valgrind.

De particular interés para los desarrolladores son las banderas de configuración utilizadas para construir Bitcoin Core sin optimizaciones para permitir una depuración más efectiva de los diversos archivos binarios resultantes.

Fabian también ha presentado sobre este tema en varias ocasiones.
Una https://btctranscripts.com/scalingbitcoin/tel-aviv-2019/edgedevplusplus/debugging-bitcoin/[transcripción^] de su charla edgedevplusplus está disponible.