:page-title: Análisis técnico detallado
:page-nav_order: 80
:page-parent: Arqueitectura
== Análisis técnico detallado

lsilva01 ha escrito un análisis técnico detallado de la arquitectura de Bitcoin Core como parte de la Documentación de Onboarding de Bitcoin Core en <<1.0_bitcoin_core_architecture.asciidoc[Bitcoin Architecture]>>.

Una vez que hayas obtenido una visión general de la arquitectura del programa, puedes aprender más detalles sobre qué archivos de código implementan qué funcionalidades desde [1.1_regions.asciidoc[Bitcoin Core regions]].

James O'Beirne ha grabado 3 videos que detallan cómo está estructurado el código, cómo funciona el sistema de construcción, qué herramientas para desarrolladores existen, así como cuál es la función principal de muchas partes del código. 

. https://www.youtube.com/watch?v=J1Ru8V36z_Y[Recorrido arquitectónico de Bitcoin Core (parte 1 de 3)^]
. https://www.youtube.com/watch?v=RVWcUnpZX4E[Recorrido arquitectónico de Bitcoin Core (parte 2 de 3)^]
. https://www.youtube.com/watch?v=UiD5DZU9Zp4[Recorrido arquitectónico de Bitcoin Core (parte 3 de 3)^]

ryanofsky ha escrito una práctica https://github.com/ryanofsky/bitcoin/blob/pr/libs/doc/design/libraries.md[guía^] que cubre las diferentes bibliotecas contenidas dentro de Bitcoin Core, junto con algunas de sus convenciones y un gráfico de dependencia para ellos. En términos generales, el deseo es que el proyecto Bitcoin Core se vuelva más modular y menos monolítico con el tiempo.
