:page-title: Principios generales de diseño
:page-nav_order: 10
:page-parent: Arquitectura
== Principios generales de diseño

Durante la última década, a medida que el alcance, la complejidad y la cobertura de pruebas del código han aumentado, ha habido un esfuerzo general no solo para descomponer Bitcoin Core de su estructura monolítica, sino también para convertirlo en una colección de subsistemas autónomos.
La razón de este objetivo es que esto hace que los componentes sean más fáciles de razonar, más fáciles de probar y menos propensos a violaciones de capas, ya que los subsistemas pueden contener una vista completa de toda la información que necesitan para operar.

Los subsistemas pueden ser notificados de eventos relevantes para ellos y tomar las acciones apropiadas por su cuenta.
En el lado de la GUI/QT, esto se maneja con señales y ranuras, pero en el demonio principal esto sigue siendo en gran medida un patrón de productor/consumidor.

Los diversos subsistemas a menudo tienen el sufijo `Manager` o `man`, por ejemplo, `CConnman` o `ChainstateManager`.

TIP: La "C" adicional en `CConnman` es un vestigio de la https://en.wikipedia.org/wiki/Hungarian_notation[notación húngara^] utilizada originalmente por Satoshi.
Esto se está eliminando gradualmente a medida que el código afectado se modifica durante otros cambios.

Puedes ver algunos (pero no todos) de estos subsistemas siendo inicializados en https://github.com/bitcoin/bitcoin/blob/v23.0/src/init.cpp#L1113[_init.cpp#AppInitMain()_^].

Hay una preferencia reciente por favorecer python sobre bash/sh para scripting, por ejemplo, para linters, pero muchos scripts de shell permanecen en su lugar para CI y scripts en contrib/.
