:page-title: Flujo de desarrollo
:page-nav_order: 10
:page-parent: Descripción general y proceso de desarrollo
== Flujo de desarrollo

Bitcoin Core utiliza un flujo de trabajo basado en GitHub para el desarrollo.
La función principal de GitHub en el flujo de trabajo es discutir parches y conectarlos con comentarios de revisión.

Mientras que algunos otros proyectos prominentes, por ejemplo, el núcleo de Linux, usan el correo electrónico para solicitar comentarios y revisiones, Bitcoin Core ha usado GitHub durante muchos años.
Inicialmente, Satoshi distribuía el código a través de correos electrónicos privados y alojando archivos fuente en bitcoin.org, y luego en SourceForge (que usaba SVN pero en ese momento no tenía una función de solicitud de extracción).
Los primeros revisores enviaban cambios usando parches, ya sea a través de intercambio de correos electrónicos con Satoshi, o publicándolos en el foro de bitcoin.

En agosto de 2009, el código fuente fue movido a GitHub por Sirius, y desde entonces el desarrollo ha permanecido allí y ha utilizado los flujos de trabajo de GitHub.

=== Uso de GitHub

El lado de GitHub del flujo de trabajo de Bitcoin Core para los Contribuidores consiste principalmente en:

* Issues
* PRs
* Revisiones
* Comentarios

Generalmente, los issues se utilizan para dos propósitos:

. Publicar problemas conocidos con el software, por ejemplo, informes de errores, registros de fallos
. Solicitar comentarios sobre posibles cambios sin proporcionar el código asociado, como sería necesario en un PR.

GitHub proporciona su propia https://guides.github.com/features/issues/[guía^] sobre el dominio de Issues que vale la pena leer para comprender el conjunto de características disponibles al trabajar con un issue.

Los PRs son donde los Contribuidores pueden enviar su código contra la base de código principal y solicitar comentarios sobre el concepto, el enfoque tomado para la implementación y la implementación en sí.

Los PRs y Issues a menudo están vinculados entre sí:

[example]
====
Un flujo de trabajo común es cuando se abre un Issue para informar un error.
Después de replicar el problema, un Contribuidor crea un parche y luego abre un PR con sus cambios propuestos.

En este caso, el Contribuidor debería, además de los comentarios sobre el parche, referenciar que el parche soluciona el problema.
Para un parche que soluciona el problema 22889, esto se haría escribiendo "fixes #22889" en la descripción del PR o en un mensaje de confirmación.
En este caso, la sintaxis "fixes #issue-number" es detectada por el https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue[vinculador de solicitudes de extracción^] de GitHub, que cierra automáticamente el issue cuando el PR es fusionado.
====

Otro caso de uso de los Issues es solicitar comentarios sobre ideas que podrían requerir cambios _significativos_.
Esto ayuda a liberar el proyecto de tener demasiados PRs abiertos que no están listos para revisión y podrían desperdiciar el tiempo de los revisores.
Además, este flujo de trabajo también puede ahorrar tiempo valioso a los Contribuidores, ya que una idea podría ser identificada como poco probable de ser aceptada _antes_ de que el contribuidor pase su tiempo escribiendo el código.

La mayoría de los cambios de código en bitcoin se proponen directamente como PRs, no es necesario abrir un Issue para cada idea antes de implementarla, a menos que pueda requerir cambios significativos.
Además, otros Contribuidores (y posibles Revisores) a menudo estarán de acuerdo con el enfoque de un cambio, pero querrán "ver la implementación" antes de poder realmente juzgarlo.

Por lo tanto, GitHub se utiliza para ayudar a almacenar y rastrear revisiones a PRs de manera pública.

Los Comentarios (dentro de Issues, PRs, Proyectos, etc.) son donde todos los usuarios de (GitHub) pueden discutir aspectos relevantes del elemento y tener un historial de esas discusiones preservado para referencia futura.
A menudo, los Contribuidores que tienen discusiones "informales" sobre cambios en, por ejemplo, IRC, serán aconsejados de que deberían reflejar la esencia de su conversación como un comentario en GitHub, para que la justificación detrás de un cambio propuesto sea clara y esté registrada.
