:page-title: Estructura de la biblioteca
:page-nav_order: 50
:page-parent: Arquitectura
:mermaid-puppeteer-config: ./puppeteer-config.json
== Estructura de la biblioteca

La compilación de Bitcoin Core produce varias bibliotecas, algunas de las cuales están diseñadas para ser utilizadas internamente y otras que están diseñadas para ser reutilizadas por aplicaciones externas.
Las bibliotecas utilizadas internamente generalmente tienen APIs inestables que las hacen inadecuadas para la reutilización, pero `libbitcoin_consensus` y `libbitcoin_kernel` están diseñadas para ser reutilizadas por aplicaciones externas.

Bitcoin Core tiene una https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md[guía^] que describe las diversas bibliotecas, sus convenciones y sus distintas dependencias.
El gráfico de dependencias se muestra a continuación para mayor comodidad, pero puede no estar actualizado con el documento de Bitcoin Core.

[id=library-dependency-graph]
.Gráfico de dependencias de la biblioteca de Bitcoin
[mermaid, target=bitcoin-lib-dependencies]
....
flowchart TB
    bitcoin-wallet --> libbitcoin_wallet_tool
    bitcoin-wallet --> libbitcoin_wallet

    bitcoin-qt ---> libbitcoin_wallet
    bitcoin-qt ---> libbitcoinqt
    bitcoin-qt ---> libbitcoin_node

    bitcoind ---> libbitcoin_wallet
    bitcoind --> libbitcoin_node

    bitcoin-cli ---> libbitcoin-cli

    libbitcoin_wallet_tool --> libbitcoin_wallet
    libbitcoin_wallet_tool --> libbitcoin_util

    libbitcoin-cli --> libbitcoin_common
    libbitcoin-cli --> libbitcoin_util

    libbitcoin_node --> libbitcoin_common
    libbitcoin_node --> libbitcoin_consensus
    libbitcoin_node --> libbitcoin_kernel
    libbitcoin_node --> libbitcoin_util

    libbitcoinqt --> libbitcoin_util
    libbitcoinqt --> libbitcoin_common

    libbitcoin_wallet --> libbitcoin_util
    libbitcoin_wallet --> libbitcoin_common

    libbitcoin_common --> libbitcoin_util
    libbitcoin_common --> libbitcoin_consensus

    libbitcoin_kernel --> libbitcoin_consensus
    libbitcoin_kernel --> libbitcoin_util

    classDef types fill:green,color:white,stroke:green;
    class bitcoin-wallet,bitcoind,bitcoin-cli,bitcoin-qt types
....

Se deduce que los cambios en la API de las bibliotecas que están orientadas internamente pueden realizarse ligeramente más fácilmente que para las bibliotecas con APIs orientadas externamente, para las cuales se debe tener más cuidado en la compatibilidad.
