:page-title: Localizaci贸n del c贸digo de consenso
:page-nav_order: 0
:page-parent: Consenso and Validaci贸n
include::links-onepage.adoc[]
[[consensus_in_bitcoin_core]]
== Consenso en Bitcoin Core

Naturalmente, se podr铆a suponer que todo el c贸digo relacionado con el consenso se podr铆a encontrar en el directorio _src/consensus/_, sin embargo, este no es del todo el caso.
Los componentes del c贸digo relacionado con el consenso se pueden encontrar en la base de c贸digo de bitcoin nore en varios archivos, incluidos, entre otros:

[#consensus-components,listing]
----
 bitcoin
   src
     consensus
     script
      interpreter.cpp
     validation.h
     validation.cpp
----

Las funciones cr铆ticas de consenso tambi茅n se pueden encontrar cerca del c贸digo que podr铆a afectar si un nodo considera una transacci贸n o bloqueo v谩lido.
Esto podr铆a extenderse, por ejemplo, el almacenamiento de bloques XREF: consensus-bugs.Adoc#database_consensus [base de datos].

A continuaci贸n se muestra una lista abreviada de algunas de las funciones y variables de consenso m谩s notables.

.Algunas funciones y variables de consenso
[cols="2,4"]
|===
|File |Objects

|_src/consensus/amount.h_
|`COIN`, `MAX_MONEY`, `MoneyRange()`

|_src/consensus/consensus.h_
|`BLOCK{SIZE\|WEIGHT\|SIGOPS_COST}`, `COINBASE_MATURITY`, `WITNESS_SCALE_FACTOR`, `MIN_TX_WEIGHT`

|_src/consensus/merkle.{h\|cpp}_
|`ComputeMerkleRoot(),` `BlockMerkleRoot(),` `BlockWitnessMerkleRoot()`

|_src/consensus/params.h_
|`BuriedDeployment`, `Params`(buried blocks which are valid but known to fail default script verify checks, BIP height activations, PoW params)

|_src/consensus/tx_check.{h\|cpp}_
|`CheckTransaction()`

|_src/consensus/tx_verify.{h\|cpp}_
|`CheckTxInputs(),` `Get{Legacy}SigOpCount()`, `IsFinalTx(),` `SequenceLock(s)()`

|_src/consensus/validation.h_
|`TxValidationResult` (validation result reason), `BlockValidationResult` (validation result reason), `ValidationState`, `Get{Transaction\|Block\|TransactionInput}Weight()`

|===
