:page-title: Pruebas manuales de un test funcional
:page-nav_order: 100
:page-parent: Overview and Development Process
==== Pruebas manuales mientras se ejecuta un test funcional

Ejecutar regtest como se describe permite comenzar desde cero con una cadena vacía, una billetera vacía y sin estado existente.

Una forma efectiva de usar regtest es iniciar una https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/functional_test_framework.asciidoc[prueba funcional^] e insertar un punto de interrupción de depuración en Python.
Puedes establecer un punto de interrupción en una prueba agregando `import pdb; pdb.set_trace()` en el punto de parada deseado; cuando el script llegue a este punto, verás el prompt del depurador `(Pdb)`, en el cual puedes escribir `help` y ver y hacer todo tipo de cosas útiles.

Mientras la prueba (Python) está pausada, aún puedes controlar el nodo usando `bitcoin-cli`.
Primero necesitas buscar el directorio de datos para el/los nodo(s), como se muestra a continuación:

[source,bash,options=nowrap]
----
$ ps alx | grep bitcoind
0  1000   57478   57476  20   0 1031376 58604 pipe_r SLl+ pts/10    0:06 /g/bitcoin/src/bitcoind -datadir=/tmp/bitcoin_func_test_ovsi15f9/node0 -logtimemicros -debug (...)
0  1000   57479   57476  20   0 965964 58448 pipe_r SLl+ pts/10     0:06 /g/bitcoin/src/bitcoind -datadir=/tmp/bitcoin_func_test_ovsi15f9/node1 -logtimemicros -debug (...)
----

With the `-datadir` path you can look at the `bitcoin.conf` files within the data directories to see what config options are being specified for the test (there's always `regtest=1`) in addition to the runtime options, which is a good way to learn about some advanced uses of regtest.

In addition to this, we can use the `-datadir=` option with `bitcoin-cli` to control specific nodes, e.g.:

[source,bash,options=nowrap]
----
$ src/bitcoin-cli -datadir=/tmp/bitcoin_func_test_ovsi15f9/node0 getblockchaininfo
----

////
Agrega `import time; time.sleep(600)` en algún lugar de una prueba funcional (que es solo un script de Python) para suspender la prueba en ese punto durante 10 minutos. (puedes agregar una declaración `print("paused")` justo antes de la llamada a `sleep()` para saber que se ha alcanzado ese punto)

Esto tiene la ventaja adicional (sobre llamar a `time.sleep()`), de que puedes ejecutar la prueba paso a paso mientras también interactúas manualmente con los nodos, combinando pruebas automatizadas y manuales.

////
