:page-title: Investigación de cambios pasados
:page-nav_order: 60
:page-parent: Overview and Development Process
=== Arqueología del código

Cuando se considera cambiar el código, puede ser útil tratar de entender primero la razón detrás de por qué se implementó de esa manera originalmente.
Una de las mejores maneras de hacer esto es utilizando una combinación de herramientas de git:

* `git blame`
* `git log -S`
* `git log -G`
* `git log -p`
* `git log -L`

Así como las discusiones en varios lugares del repositorio de GitHub.

==== git blame

El comando `blame` de git te mostrará cuándo (y por quién) se cambió por última vez una línea particular de código.

Por ejemplo, si revisamos Bitcoin Core en https://github.com/bitcoin/bitcoin/tree/v22.0[v22.0^] y estamos planeando hacer un cambio relacionado con el `m_addr_send_times_mutex` que se encuentra en _src/net_processing.cpp_, podríamos querer saber más sobre su historia antes de tocarlo.

Con `git blame` podemos encontrar a la última persona que tocó este código:

[source,bash,options="nowrap"]
----
# Encuentra el número de línea para blame
$ grep -n m_addr_send_times_mutex src/net_processing.cpp
233:    mutable Mutex m_addr_send_times_mutex;
235:    std::chrono::microseconds m_next_addr_send GUARDED_BY(m_addr_send_times_mutex){0};
237:    std::chrono::microseconds m_next_local_addr_send GUARDED_BY(m_addr_send_times_mutex){0};
4304:    LOCK(peer.m_addr_send_times_mutex);
----

[source,bash,options=nowrap]
----
$ git blame -L233,233 src/net_processing.cpp

76568a3351 (John Newbery 2020-07-10 16:29:57 +0100 233)     mutable Mutex m_addr_send_times_mutex;
----

Con esta información podemos buscar fácilmente ese commit para obtener un contexto adicional:

[source,bash,options=nowrap]
----
$ git show 76568a3351

───────────────────────────────────────
commit 76568a3351418c878d30ba0373cf76988f93f90e
Author: John Newbery <john@johnnewbery.com>
Date:   Fri Jul 10 16:29:57 2020 +0100

    [net processing] Move addr relay data and logic into net processing

----

Así que ahora hemos aprendido que este mutex fue movido aquí por John desde _net.{cpp|h}_ en su toque más reciente.
Veamos qué más podemos averiguar sobre él.

==== git log -S

`git log -S` nos permite buscar commits donde esta línea fue _modificada_ (no donde solo fue movida, para eso usa `git log -G`).

[TIP]
====
Una 'modificación' (vs. un 'movimiento') en la jerga de git es el resultado de instancias desiguales del término de búsqueda en las secciones de agregar/eliminar de los diffs del commit.

Esto implica que este término ha sido agregado o eliminado en el commit.
====

[source,bash,options=nowrap]
----
$ git log -S m_addr_send_times_mutex
───────────────────────────────────────
commit 76568a3351418c878d30ba0373cf76988f93f90e
Author: John Newbery <john@johnnewbery.com>
Date:   Fri Jul 10 16:29:57 2020 +0100

    [net processing] Move addr relay data and logic into net processing

───────────────────────────────────────
commit ad719297f2ecdd2394eff668b3be7070bc9cb3e2
Author: John Newbery <john@johnnewbery.com>
Date:   Thu Jul 9 10:51:20 2020 +0100

    [net processing] Extract `addr` send functionality into MaybeSendAddr()

    Reviewer hint: review with

     `git diff --color-moved=dimmed-zebra --ignore-all-space`

───────────────────────────────────────
commit 4ad4abcf07efefafd439b28679dff8d6bbf62943
Author: John Newbery <john@johnnewbery.com>
Date:   Mon Mar 29 11:36:19 2021 +0100

    [net] Change addr send times fields to be guarded by new mutex

----

Ahora aprendemos que John también agregó originalmente esto a _net.{cpp|h}_, antes de moverlo a _net_processing.{cpp|h}_ como parte de un esfuerzo por separar los datos y la lógica de retransmisión de `addr` de _net.cpp_.

==== git log -p

`git log -p` (usualmente también dado con un argumento de nombre de archivo) sigue cada mensaje de commit con un _parche_ (diff) de los cambios realizados por ese commit a ese archivo (o archivos).
Esto es similar a `git blame` excepto que `git blame` muestra la fuente de solo las líneas _actualmente_ en el archivo.

==== git log -L

El parámetro `-L` proporcionado a git log te permitirá rastrear ciertas líneas de un archivo a través de un rango dado por `<start,<end>`.

Sin embargo, las versiones más nuevas de git también te permitirán proporcionar `git log -L` con un nombre de función y un archivo, usando:

[source,shell]
----
git log -L :<funcname>:<file>
----

Esto mostrará los commits que modificaron esta función en tu paginador.

==== git log --follow _file..._

Uno de los https://github.com/bitcoin/bitcoin/pull/9260[renombramientos de archivos^] más famosos fue _src/main.{h,cpp}_ a _src/validation.{h,cpp}_ en 2016.
Si simplemente ejecutas `git log src/validation.h`, el commit más antiguo mostrado es uno que implementó el renombramiento.
`git log --follow src/validation.h` mostrará los mismos commits recientes seguidos por los commits más antiguos de _src/main.h_.

Para ver la historia de un archivo que ha sido eliminado, especifica " -- " antes del nombre del archivo, como:
[source,bash]
----
git log -- some_removed_file.cpp
----

==== Discusión de PR

Para obtener aún más contexto sobre el cambio, podemos aprovechar GitHub y echar un vistazo a los comentarios en el PR donde se introdujo este mutex (o en cualquier commit posterior donde fue modificado).
Para encontrar el PR puedes pegar el hash del commit (`4ad4abcf07efefafd439b28679dff8d6bbf62943`) en GitHub, o listar los commits de merge en orden inverso, mostrando el merge más antiguo con el commit en la parte superior para mostrar el número de PR específico, por ejemplo:

[source,bash,options=nowrap]
----
$ git log --merges --reverse --oneline --ancestry-path 4ad4abcf07efefafd439b28679dff8d6bbf62943..upstream | head -n 1

d3fa42c79 Merge bitcoin/bitcoin#21186: net/net processing: Move addr data into net_processing
----

Leer sobre https://github.com/bitcoin/bitcoin/pull/21186[PR#21186^] con suerte nos proporcionará más contexto que podamos usar.

[example]
====
Podemos ver desde el https://github.com/bitcoin/bitcoin/issues/19398#issue-646725848[issue 19398^] vinculado cuál fue la motivación para este movimiento.
====
