:page-title: Maduración de la PR
:page-nav_order: 130
:page-parent: Descripción general y proceso de desarrollo
==== ACK / NACK

Si estás comunicándote en un Issue o PR, es posible que te encuentres con "ACK"s y "NACK"s (o incluso "approach (N)ACK" o similar).
ACK, o "acknowledge" generalmente significa que el comentarista aprueba lo que se está discutiendo previamente.
NACK significa que tienden a no aprobar.

¿Qué deberías hacer si tu PR recibe NACKs o una mezcla de ACKs y NACKs?
Nuevamente, no hay reglas estrictas, pero generalmente deberías tratar de considerar todos los comentarios como críticas constructivas.
Esto puede ser difícil cuando los contribuyentes veteranos parecen pasar y con un solo "NACK" rechazan tu idea, pero en realidad presenta un buen momento para pausar y reflexionar sobre _por qué_ alguien no está de acuerdo con el camino que has presentado.

Aunque nuevamente no hay "reglas" o "sistemas de medición" estrictos con respecto a los (N)ACKs, los mantenedores -- cuyo trabajo es medir si un cambio tiene consenso antes de fusionarlo -- a menudo usarán su discreción para atribuir más peso a los (N)ACKs de los contribuyentes que sienten que tienen un buen entendimiento del código en esta área.

Esto tiene sentido por muchas razones, pero imaginemos el escenario extremo donde miembros de un hilo de Reddit/Twitter (u otro grupo) todos "https://www.dictionary.com/e/slang/brigading/[brigade]" una cierta solicitud de extracción en GitHub, llenándola con decenas o incluso cientos de NACKs...
