:page-title: Revisión de código
:page-nav_order: 20
:page-parent: Overview and Development Process
=== Revisión de código

Jon Atack proporciona una guía para revisar un PR de Bitcoin Core en su artículo https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core[How To Review Pull Requests in Bitcoin Core^].

// Archivado en https://archive.is/MyohE
La https://github.com/glozow/bitcoin-notes/blob/master/review-checklist.md[lista de verificación de revisión^] de Gloria Zhao detalla cómo podría ser una "buena" revisión, junto con algunos ejemplos de lo que ella personalmente busca en una revisión.
Además de esto, detalla cómo los posibles Revisores pueden abordar un nuevo PR que han elegido revisar, junto con el tipo de preguntas que deberían estar haciendo (y respondiendo) para proporcionar una revisión completa y útil.
Algunos ejemplos de las áreas temáticas que Gloria cubre incluyen el área temática de la PR, la motivación, los inconvenientes, el enfoque, los riesgos de seguridad y privacidad, la implementación de la idea, el impacto en el rendimiento, la concurrencia y la pruebas.
