:page-title: Organización del código fuente
:page-nav_order: 60
:page-parent: Arquitectura

== Organización del código fuente

El Issue https://github.com/bitcoin/bitcoin/issues/15732[#15732^] describe cómo el proyecto Bitcoin Core está tratando de organizar las bibliotecas y su código fuente asociado, copiado a continuación para mayor conveniencia:

> Aquí está cómo estoy pensando en la organización:
> 
>     * `libbitcoin_server.a`, `libbitcoin_wallet.a` y `libbitcoinqt.a` deberían ser todas dependencias terminales. Deberían poder depender de otros símbolos en otras bibliotecas, pero ninguna otra biblioteca [...]
> 
>     * `libbitcoin_consensus.a` debería ser una biblioteca independiente que no dependa de símbolos en otras bibliotecas mencionadas aquí.
> 
>     * `libbitcoin_common.a` y `libbitcoin_util.a` parecen ser muy intercambiables en este momento y dependen mutuamente entre sí. Creo que deberíamos fusionarlas en una sola biblioteca, o crear un nuevo nivel superior [...]
> 
> 
> Con el tiempo, creo que sería bueno si la organización del código fuente reflejara la organización de las bibliotecas. Creo que sería bueno si todos los archivos fuente de `libbitcoin_util` vivieran en `src/util`, todos los archivos fuente de `libbitcoin_consensus[...]

Puedes seguir el progreso de estos cambios siguiendo los enlaces desde el issue a los PRs asociados.

El https://github.com/bitcoin/bitcoin/issues/24303[proyecto^] `libbitcoin-kernel` proporcionará más limpiezas y mejoras en esta área.

Si deseas explorar por ti mismo qué fuentes requieren ciertas bibliotecas en la base de código actual, puedes abrir el archivo `src/Makefile.am` y buscar `_SOURCES`.
