:page-title: Comenzando con el desarrollo
:page-nav_order: 110
:page-parent: Descripción general y proceso de desarrollo
=== Comenzando con el desarrollo

Uno de los roles más demandados del proyecto es el de revisión de código, ¡y de hecho, esta es también una de las mejores maneras de familiarizarse con la base de código!
Revisar algunos PRs y agregar tus comentarios de revisión al PR en GitHub puede ser muy valioso para ti, el autor del PR y la comunidad de bitcoin.
Esta publicación del blog de Google Code Health https://testing.googleblog.com/2018/05/code-health-understanding-code-in-review.html[^] ofrece buenos consejos sobre cómo llevar a cabo la revisión de código y superar la "sensación de que no eres tan inteligente como el programador que escribió el cambio".
Si vas a hacer algunas preguntas como parte de la revisión, intenta mantener las preguntas https://testing.googleblog.com/2019/11/code-health-respectful-reviews-useful.html[respetuosas^].

También hay un https://bitcoincore.reviews/[Club de Revisión^] de PR de Bitcoin Core que se lleva a cabo semanalmente en IRC, lo cual proporciona un punto de entrada ideal a la base de código de Bitcoin Core.
Se selecciona un PR, se proporcionan preguntas sobre el PR de antemano para ser discutidas en el canal de IRC irc.libera.chat #bitcoin-core-pr-reviews y un anfitrión liderará la discusión sobre los cambios.

Además de la revisión, hay 3 vías principales que podrían llevarte a enviar tu *propio* PR al repositorio:

. Encontrar un `good first issue`, etiquetado en el https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[rastreador de problemas^]
. Arreglar un error
. Agregar una nueva característica (¿que deseas para ti mismo?)

Elegir un "good first issue" de un área de la base de código que te parezca interesante a menudo es un buen enfoque.
Esto se debe a que estos problemas han sido algo implícitamente "concept ACKed" por otros colaboradores como "algo que probablemente valga la pena que alguien trabaje en ello".
No confundas esto con que si trabajas en ello, es seguro que se fusionará.

Si no tienes en mente una corrección de errores o una nueva característica y estás luchando por encontrar un buen primer problema que te parezca adecuado, no te preocupes.
En su lugar, sigue revisando los PRs de otros colaboradores para continuar mejorando tu comprensión del proceso (y la base de código) mientras observas el rastreador de problemas en busca de algo que te guste.

Cuando hayas decidido en qué trabajar, es hora de echar un vistazo al comportamiento actual de esa parte del código y quizás más importante, tratar de entender _por qué_ se implementó originalmente de esta manera.
Este proceso de "arqueología" de la base de código será invaluable en el futuro cuando intentes aprender sobre otras partes de la base de código por tu cuenta.
