:page-title: Subárboles y PIMPL
:page-nav_order: 90
:page-parent: Arquitectura
include::links-onepage.adoc[]
[[subtrees]]
== Subárboles

Varias partes del repositorio (LevelDB, CRC32C, SECP256K1, etc.) son subárboles de software mantenidos en otros lugares.

Algunos de estos son mantenidos por desarrolladores activos de Bitcoin Core, en cuyo caso los cambios deben ir directamente aguas arriba sin ser predominantes directamente contra el proyecto.
Se fusionarán en la próxima fusión de subárbol.

Otros son proyectos externos sin una relación estrecha con nuestro proyecto.

Hay una herramienta en `test/lint/git-subtree-check.sh` para verificar un directorio de subárbol en busca de consistencia con su repositorio ascendente.

Consulte el completo https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#subtrees[subtrees
] documentación para obtener más información.

== Separación de implementación

Muchas de las clases encontradas en toda la base de código utilizan la técnica PIMPL para separar su implementación de la representación externa.
Consulte xref:apendix.adoc#Pimpl-Technique[técnica PIMPL] en el Apéndice para obtener más información.
