:page-title: Resumen de pruebas
:page-nav_order: 30
:page-parent: Arquitectura
:mermaid-puppeteer-config: ./puppeteer-config.json
== Resumen de pruebas

.Resumen de pruebas
[%autowidth]
|===
|Herramienta |Uso

|tests unitarios
|`make check` or `./src/test_bitcoin`

|tests funcionales
|`test/functional/test_runner.py`

|comprobaciones de lint
|See the https://github.com/bitcoin/bitcoin/blob/master/test/lint/README.md#running-locally[documentation^]

|fuzz
|See the https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md[documentation^]

|pruebas de utilidades
|`test/util/test_runner.py`

|===

Bitcoin Core también está introduciendo "pruebas de estrés" (funcionales) que desafían el programa mediante interrupciones y archivos faltantes para asegurar que fallemos de manera controlada, por ejemplo, las pruebas introducidas en https://github.com/bitcoin/bitcoin/pull/23289[PR#23289^].

=== Estructura del directorio de pruebas

El siguiente diagrama ofrece una breve descripción de cómo están estructuradas las pruebas dentro del directorio fuente.

ADVERTENCIA: Este diagrama **no** es exhaustivo e incluye simplificaciones.

NOTA: las líneas discontinuas indican componentes opcionales.

NOTA: Los `fuzz_targets` se encuentran en la carpeta `test`, sin embargo, las pruebas de fuzz se ejecutan a través del `test_runner` en src/test, por lo que apuntamos fuzz allí.

NOTA: Los `qa_assets` se encuentran en un repositorio https://github.com/bitcoin-core/qa-assets[separado^] por completo, ya que son bastante grandes (~3.5GB de tamaño del repositorio y ~13.4GB al clonar).

.Estructura del directorio de pruebas
[mermaid, target=bitcoin-core-tests]
....
flowchart LR
    TR1[test_runner]
    functional --> test
    lint --> test
    util --> test
    test_framework --> functional
    TR1 --> functional

    TR2["test_runner (fuzz)"]
    fuzz_targets --> fuzz
    fuzz --> src/test
    libFuzzer -.-> fuzz
    TR2 --> fuzz
    qa-assets -.-> fuzz
    unit --> src/test
    Boost --> unit
    test_bitcoin --> unit

    classDef types fill:green,color:white,stroke:green;
    class functional,lint,util,fuzz,unit types
....

=== Cobertura de pruebas

Los informes de cobertura de pruebas de Bitcoin Core se pueden encontrar https://maflcko.github.io/b-c-cov/[aquí^].

