:page-title: Probando tus contribuciones
:page-nav_order: 40
:page-parent: Descripción general y proceso de desarrollo

==== Integración continua

Cuando se envían PRs contra el repositorio principal de Bitcoin Core, se ejecutará automáticamente una serie de https://github.com/bitcoin/bitcoin/tree/v23.0/ci[pruebas de CI^].
Estas incluyen una serie de linters y formateadores como `clang-format`, `flake8` y `shellcheck`.
Es posible (y recomendable) ejecutar estas comprobaciones localmente contra cualquier cambio que realices antes de enviarlos.

Para ejecutar los linters tú mismo, primero debes asegurarte de que tu entorno de Python y tu sistema tengan los paquetes listados en el https://github.com/bitcoin/bitcoin/blob/v23.0/ci/lint/04_install.sh[script de instalación de CI].
Luego puedes ejecutar un subconjunto decente de las comprobaciones ejecutando:

[source,bash]
----
python test/lint/lint-circular-dependencies.py

# requiere 'flake8', 'mypy', 'pyzmq', 'codespell', 'vulture'
python test/lint/lint-python.py

python test/lint/lint-whitespace.py
----

O puedes ejecutar todas las comprobaciones con:

[source,bash]
----
cd ./test/lint/test_runner/ && cargo fmt && cargo clippy && cargo run
----

NOTA: Anteriormente, estas comprobaciones eran scripts de shell (`*.sh`), pero ahora se han migrado a Python en master.
+
Si estás siguiendo con la etiqueta v23.0, es posible que aún existan como `*.sh`.

Lintear tus cambios reduce las posibilidades de enviarlos como un PR y que luego se marquen rápidamente como fallidos en CI. La página de PR de GitHub actualiza automáticamente el estado de CI.

CONSEJO: Si fallas un lint u otra comprobación de CI, forzar el envío del arreglo a tu rama cancelará las comprobaciones de CI en curso y las reiniciará.

==== Problemas de compilación

Algunos problemas en tiempo de compilación pueden ser causados por un directorio de compilación no limpio.
Los comentarios en https://github.com/bitcoin/bitcoin/issues/19330[el issue 19330^] proporcionan algunas aclaraciones y consejos sobre cómo otros colaboradores limpian sus directorios, así como algunas ideas para alias de shell para aumentar la productividad.