:page-title: Uso de una red de prueba
:page-nav_order: 90
:page-parent: Overview and Development Process
=== Pruebas

Tres tipos de redes de prueba están disponibles:

1. Testnet
2. Regtest
3. Signet

Estas tres redes usan monedas de valor cero, por lo que pueden ser utilizadas experimentalmente.

Las principales diferencias entre las redes son las siguientes:

.Comparación de diferentes redes de prueba
[cols="1h,1,1,1"]
|===================================================================================================================================
| Característica            | Testnet                        | Regtest                       | Signet

| Algoritmo de minería      | Hashing público con dificultad | Hashing local, baja dificultad| Firma de firmantes autorizados
| Programación de producción de bloques | Varía según el hashrate | A demanda                     | Intervalos confiables (por defecto 2.5 mins)
| Puerto P2P                | 18333                          | 18444                         | 38333
| Puerto RPC                | 18332                          | 18443                         | 38332
| Pares                     | Público                        | Ninguno                       | Público
| Topología                 | Orgánica                       | Manual                        | Orgánica
| Nacimiento de la cadena   | 2011-02-02                     | En el momento de uso          | 2020-09-01
| Puede iniciar reorgs      | Si Minero                      | Sí                            | No
| Uso principal             | Pruebas en red                 | Pruebas de integración automatizadas | Pruebas en red
|===================================================================================================================================

==== Signet

Signet es tanto una herramienta que permite a los desarrolladores crear sus propias redes para probar interacciones entre diferentes software de Bitcoin, como el nombre de la más popular de estas redes de prueba públicas.
Signet fue codificado en https://github.com/bitcoin/bips/tree/master/bip-0325.mediawiki[BIP 325^].

Para conectarse a la red "principal" de Signet, simplemente inicie bitcoind con la opción signet, por ejemplo, `bitcoind -signet`.
No olvide también pasar la opción signet a `bitcoin-cli` si lo usa para controlar bitcoind, por ejemplo, `bitcoin-cli -signet su_comando_aquí`.
Las instrucciones sobre cómo configurar su propia red Signet se pueden encontrar en el https://github.com/bitcoin/bitcoin/tree/master/contrib/signet/README.md[README.md^] de Signet de Bitcoin Core.
La página de Signet en la wiki de Bitcoin https://en.bitcoin.it/wiki/Signet[proporciona^] información adicional sobre Signet.

==== Regtest

Otra red de prueba llamada _regtest_, que significa _prueba de regresión_, también está disponible.
Esta red se habilita iniciando bitcoind con la opción `-regtest`.
Este es un modo completamente autónomo, que le da control total sobre el estado de la blockchain.
Los bloques pueden ser minados simplemente a pedido por el operador de la red.

Las https://github.com/chaincodelabs/bitcoin-core-onboarding/blob/main/functional_test_framework.asciidoc[pruebas funcionales^] usan este modo, pero también puede ejecutarlo manualmente.
Proporciona un buen medio para aprender y experimentar en sus propios términos.
A menudo se ejecuta con un solo nodo, pero puede ejecutarse con múltiples nodos co-localizados (locales) (la mayoría de las pruebas funcionales hacen esto).
La blockchain inicialmente contiene solo el bloque génesis, por lo que necesita minar >100 bloques para tener monedas gastables de una coinbase madura.
Aquí hay una sesión de ejemplo (después de haber construido `bitcoind` y `bitcoin-cli`):

[source,bash,options="nowrap"]
----
$ mkdir -p /tmp/regtest-datadir
$ src/bitcoind -regtest -datadir=/tmp/regtest-datadir
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir getblockchaininfo
{
  "chain": "regtest",
  "blocks": 0,
  "headers": 0,
  "bestblockhash": "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
  _(...)_
}
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir createwallet testwallet
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir -generate 3
{
  "address": "bcrt1qpw3pjhtf9myl0qk9cxt54qt8qxu2mj955c7esx",
  "blocks": [
    "6b121b0c094b5e107509632e8acade3f6c8c2f837dc13c72153e7fa555a29984",
    "5da0c549c3fddf2959d38da20789f31fa7642c3959a559086436031ee7d7ba54",
    "3210f3a12c25ea3d8ab38c0c4c4e0d5664308b62af1a771dfe591324452c7aa9"
  ]
}
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir getblockchaininfo
{
  "chain": "regtest",
  "blocks": 3,
  "headers": 3,
  "bestblockhash": "3210f3a12c25ea3d8ab38c0c4c4e0d5664308b62af1a771dfe591324452c7aa9",
  _(...)_
}
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir getbalances
{
  "mine": {
    "trusted": 0.00000000,
    "untrusted_pending": 0.00000000,
    "immature": 150.00000000
  }
}
$ src/bitcoin-cli -regtest -datadir=/tmp/regtest-datadir stop
----

Puede detener y reiniciar el nodo y utilizará el estado existente.
(Simplemente elimine el directorio de datos para comenzar de nuevo desde cero).

Blockchain Commons ofrece una guía para https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/A3_0_Using_Bitcoin_Regtest.md[Usar Bitcoin Regtest^].

==== Testnet

Testnet es una red pública de bitcoin donde la minería se realiza de la manera habitual (hashing) por mineros descentralizados.

Sin embargo, debido a una tasa de hash mucho más baja (que la red principal), testnet es susceptible a niveles extremos de volatilidad entre bloques debido a la forma en que funciona el ajuste de dificultad (DA): si un minero a escala de la red principal quiere "probar" su configuración de minería en testnet, entonces pueden causar que la dificultad aumente enormemente.
Una vez que el minero ha concluido sus pruebas, pueden eliminar toda la potencia de hash de la red de una vez.
Esto puede dejar la red con una alta dificultad que el DA tardará mucho tiempo en compensar.

Por lo tanto, se introdujo una https://en.bitcoin.it/wiki/Testnet#Differences["regla de 20 minutos"^] tal que la dificultad se reduciría al mínimo por un bloque antes de volver a su valor anterior.
Esto asegura que no haya tiempos entre bloques mayores de 20 minutos.

Sin embargo, hay un error en la implementación que significa que si este ajuste ocurre en un bloque de ajuste de dificultad, la dificultad se reduce al mínimo por un bloque pero luego no se restablece, haciéndolo permanente en lugar de un ajuste único.
Esto resultará en un gran número de bloques encontrados hasta que el DA se ponga al nivel de la potencia de hash en la red.

Por esta razón, generalmente es preferible probar cambios privados en un regtest local, o cambios públicos en un Signet.
