:page-title: Hilos
:page-nav_order: 40
:page-parent: Arquitectura
== Hilos

La función `main()` inicia el proceso principal del hilo `bitcoind`, llamado `bitcoind`.
Todos los hilos subsiguientes se inician actualmente como hijos del hilo `bitcoind`, aunque esto no es un requisito de diseño explícito.

El Desarrollador de Bitcoin Core https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#threads=[docs^] contiene una sección sobre hilos, que se resume a continuación en dos tablas, una para hilos no relacionados con la red y otra para hilos relacionados con la red.

.Hilos no relacionados con la red
[%autowidth]
|===
|Nombre |Función |Descripción

|`bitcoind`
|`main()`
|Responsable de iniciar y cerrar la aplicación, y de generar todos los sub-hilos

|`b-loadblk`
|`ThreadImport`
|Carga bloques desde archivos `blk*.dat` o `-loadblock=<archivo>` al iniciar

|`b-scriptch.x`
|`ThreadScriptCheck`
|Hilos de validación de scripts en paralelo para transacciones en bloques

|`b-http`
|`ThreadHTTP`
|Hilo Libevent para escuchar conexiones RPC y REST

|`b-httpworker.x`
|`StartHTTPServer`
|Hilos de trabajo HTTP. Hilos para atender solicitudes RPC y REST

|`b-txindex.x`
|`ThreadSync`
|Hilos de indexación. Un hilo por indexador

|`b-scheduler`
|`SchedulerThread`
|Realiza tareas asincrónicas en segundo plano, como volcar el contenido de la billetera, volcar `addrman` y ejecutar callbacks asincrónicos de `validationinterface`

|`b-torcontrol`
|`TorControlThread`
|Hilo Libevent para conexiones tor

|===

[[net_threads]]
=== Hilos relacionados con la red

.Hilos relacionados con la red
[%autowidth]
|===
|Nombre |Función |Descripción

|`b-msghand`
|`ThreadMessageHandler`
|Manejo de mensajes a nivel de aplicación (envío y recepción). Casi toda la lógica de `net_processing` y validación se ejecuta en este hilo

|`b-dnsseed`
|`ThreadDNSAddressSeed`
|Carga direcciones de pares desde el `ThreadDNS`

|`b-upnp`
|`ThreadMapPort`
|Inicio/cierre universal plug-and-play

|`b-net`
|`ThreadSocketHandler`
|Envía/Recibe datos de pares en el puerto 8333

|`b-addcon`
|`ThreadOpenAddedConnections`
|Abre conexiones de red a nodos añadidos

|`b-opencon`
|`ThreadOpenConnections`
|Inicia nuevas conexiones con pares

|`b-i2paccept`
|`ThreadI2PAcceptIncoming`
|Escucha y acepta conexiones entrantes de I2P a través del proxy I2P SAM

|===

=== Depuración de hilos

Para depurar una aplicación multi-hilo como bitcoind usando gdb, necesitarás habilitar el seguimiento de procesos secundarios.
A continuación se muestra el contenido de un archivo `threads.brk` que puede ser cargado en gdb usando `source threads.brk`, antes de comenzar a depurar bitcoind.
El archivo también carga puntos de interrupción donde se generan nuevos hilos.

.threads.brk
[source,bash]
----
set follow-fork-mode child
break node::ThreadImport
break StartScriptCheckWorkerThreads
break ThreadHTTP
break StartHTTPServer
break ThreadSync
break SingleThreadedSchedulerClient
break TorControlThread
break ThreadMessageHandler
break ThreadDNSAddressSeed
break ThreadMapPort
break ThreadSocketHandler
break ThreadOpenAddedConnections
break ThreadOpenConnections
break ThreadI2PAcceptIncoming
----
