:page-title: Archivos en el espacio de usuario
:page-nav_order: 70
:page-parent: Arquitectura
== Archivos en el espacio de usuario

Bitcoin Core almacena una serie de archivos en su directorio de datos ($DATADIR) en tiempo de ejecución.

=== Archivos de bloque y deshacer

$DATADIR/blocks/blk*.dat::
Almacena datos de bloques en formato de red en el orden recibido.

$DATADIR/blocks/rev*.dat::
Almacena datos de "deshacer" de bloques en el orden procesado.
+
[quote,Pieter Wuille,'https://bitcoin.stackexchange.com/questions/11104/what-is-the-database-for?rq=1[stackexchange]']
____
Puedes ver los bloques como 'parches' al estado de la cadena (consumen algunas salidas no gastadas y producen nuevas), y ver los datos de deshacer como parches inversos. Son necesarios para revertir la cadena[...]
____

////
TODO: bitcoin.conf, config.json, debug.log ??
////

=== Índices

Con los datos de los archivos raw block* y rev*, se pueden construir varios índices LevelDB.
Estos índices permiten una búsqueda rápida de datos sin tener que volver a escanear toda la cadena de bloques en el disco.

Algunas de estas bases de datos son obligatorias y otras son opcionales y se pueden habilitar utilizando flags de configuración en tiempo de ejecución.

Índice de Bloques::
Ubicación del sistema de archivos de los bloques + algunos metadatos

Índice de Estado de la Cadena::
Todos los UTXOs actuales + algunos metadatos

Índice de Tx::
Ubicación del sistema de archivos de todas las transacciones por txid

Índice de Filtro de Bloques::
Filtros, hashes y cabeceras de [BIP157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki)

Índice de Estadísticas de Monedas::
Estadísticas del conjunto UTXO [statistics](https://github.com/bitcoin/bitcoin/blob/b3f866a8dfd652b6339b79124843e58bd0bf3013/src/index/coinstatsindex.h#L26-L37)

[%autowidth]
|===
|Nombre |Ubicación |Opcional |Clase

|Índice de Bloques
|_$DATADIR/blocks/index_
|No
|`BlockIndex`

|Índice de Estado de la Cadena
|_$DATADIR/chainstate_
|No
|`Chainstate`

|Índice de Tx
|_$DATADIR/indexes/txindex_
|Sí
|`TxIndex`

|Índice de Filtro de Bloques
|_$DATADIR/indexes/blockfilter/<filter name>_
|Sí
|`BlockFilterIndex`

|Índice de Estadísticas de Monedas
|_$DATADIR/indexes/coinstats_
|Sí
|`CoinstatsIndex`

|===
