# see https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml for reference
name: Build
on:
  pull_request:
    branches: [main, master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages-build
  cancel-in-progress: false
jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          cache-version: 0
      - name: Setup Node.JS 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Generate Site
        run: |
          bundle
          make all
        env:
          JEKYLL_ENV: production
          ADD_JEKYLL_ARGS: --baseurl "${{ steps.pages.outputs.base_path }}"
